let rezultate = {
    "Alba": 1,
    "Arad": 1,
    "Arges": 1,
    "Bacau": 1,
    "Bihor": 1,
    "Bistrita-Nasaud": 1,
    "Botosani": 1,
    "Braila": 1,
    "Brasov": 1,
    "Bucuresti": 1,
    "Buzau": 1,
    "Calarasi": 1,
    "Caras-Severin": 1,
    "Cluj": 1,
    "Constanta": 1,
    "Covasna": 1,
    "Dambovita": 1,
    "Dolj": 1,
    "Galati": 1,
    "Giurgiu": 1,
    "Gorj": 1,
    "Harghita": 1,
    "Hunedoara": 1,
    "Ialomita": 1,
    "Iasi": 1,
    "Ilfov": 1,
    "Maramures": 1,
    "Mehedinti": 1,
    "Mures": 1,
    "Neamt": 1,
    "Olt": 1,
    "Prahova": 1,
    "Salaj": 1,
    "Satu Mare": 1,
    "Sibiu": 1,
    "Suceava": 1,
    "Teleorman": 1,
    "Timis": 1,
    "Tulcea": 1,
    "Valcea": 1,
    "Vaslui": 1,
    "Vrancea": 1
};

export const data = rezultate;
export const maxValue = 75;